# Site Configuration

theme: default
lang: "fr"

plugins: []

google_analytics_id:

title: "Baladiati"

avatar: "https://lh3.googleusercontent.com/d/1nR_JaIn6Nl2lgh96VQqcLPgTT3swwWXl=w1000?authuser=0"

name: "Baladiati"

tagline: >-
  Application citoyenne permettant de signaler les anomalies dans votre ville.

links:
  - link:
      icon: "fa-brands fa-google-play"
      text: "Télécharger sur Google Play"
      url: "https://play.google.com/store/apps/details?id=com.baladiati"
      alt: "Baladiati sur Google Play"
      title: "Télécharger Baladiati sur Google Play"
      target: "_blank"

  - link:
      icon: "fa-brands fa-app-store-ios"
      text: "Télécharger sur l’App Store"
      url: "https://apps.apple.com/app/baladiati"
      alt: "Baladiati sur l’App Store"
      title: "Télécharger Baladiati sur l’App Store"
      target: "_blank"

socials: []

footer: >
    Merci d'utiliser Baladiati pour améliorer votre ville.

copyright: >
  © 2024 Baladiati. Tous droits réservés.
